# theme="fleet_dark"
theme="chocolate"
# theme="rose_pine"
# theme="catppuccin_mocha"
# theme="carbonfox"
# theme="jetbrains_dark"


[editor]
line-number = "relative" # or keep absolute..
mouse = false # but we can still scroll yay!
scrolloff = 1 # leave 1 to see decorator attached and stuff
middle-click-paste = false # this is the most horrible thing ever...
cursorline = true # default : false... nande ??
# gutters = ["diff","line-numbers","spacer","diagnostics","spacer"]
gutters = ["diff","line-numbers","spacer"] # hate when the gutter gets really big
completion-trigger-len = 2 # default 2
bufferline = "always" # so that we can get away without putting the file path in the statuline
color-modes = true
# popup-border = "all"

# [editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"


# [editor.whitespace]
# render="all"

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"
space = "none" # there is no settings for trailing whitespaces :(


[editor.indent-guides]
render = true
# character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.lsp]
enable = true
snippets = true
display-inlay-hints = true
auto-signature-help = true
display-progress-messages=true

[editor.statusline.mode]
insert = "Insert"
normal = "Normal"
select = "Select" 

[editor.statusline]
left = ["mode","spinner"]
center = ["version-control"]
right = ["spinner","diagnostics","spacer","position-percentage"]


[keys.normal]
";" = ["repeat_last_motion"]
# Muscle memory
# {} have no conflicts..
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
# 0 = "goto_first_nonwhitespace"
# "$" = "goto_line_end"
# usually x does not extend
x = ["select_mode", "extend_to_line_bounds"]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]


[keys.normal."]"]
"]" = ":buffer-next"
[keys.normal."["]
"[" = ":buffer-previous"

[keys.normal."-"]
"t" = {l = ":theme rose_pine_dawn", d=":theme chocolate", f =":theme fleet_dark"}
# quick eb
# we will probably remove it ... better not to practice this
"f" = "file_picker_in_current_buffer_directory"
"F" = ":format"
"-" = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
w = {w = ":w", q = ":wq"}
q = {b =":buffer-close!", q = ":q!"}
v = ":vsplit"
h = ":hsplit"
c = {o =":config-open", r = ":config-reload"}
g = [":vsplit-new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

# "-" = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
# old
# C-y = ":sh zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"

[keys.select]
"q" = [":reflow","collapse_selection"]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

# ~ in helix
# u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
# U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Make selecting lines in visual mode behave sensibly
# without this it selects after or before the home line
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
