# ========================= PYLSP===========
# [[language]]
# name = "python"
# language-servers = [ { name = "pylsp", except-features = [ "format" ] }, "ruff"]
# auto-format = true

# [language-server.pylsp.config.pylsp.plugins]
# ruff.enabled = false
# autopep8.enabled = false
# flake8.enabled = false
# mccabe.enabled = false
# pycodestyle.enabled = false
# pyflakes.enabled = false
# pylint.enabled = false
# yapf.enabled = false

#=================== Pyrefly============
# [language-server.pyrefly]
# command = "pyrefly"
# args = ["lsp"]

# [[language]]
# name = "python"
# language-servers = ["pyrefly"]
# 
# ========================= Based Pyright===========

# [language-server.basedpyright]
# command = "basedpyright-langserver"
# args = ["--stdio"]

# [language-server.basedpyright.config.basedpyright]
# analysis.diagnosticMode = "openFilesOnly"
# diagnostics.reportUnknownParameterType = "none"
# diagnostics.reportUnknownArgumentType = "none"
# diagnostics.reportUnknownLambdaType = "none"
# diagnostics.reportUnknownVariableType = "none"
# diagnostics.reportUnknownMemberType = "none"

# [[language]]
# name = "python"
# language-servers = ["basedpyright"]

#============= ruff (pretty bad... doesnt have hover or goto definition)
# [language-server.ruff]
# command = "ruff"
# args = ["server"]
# [[language]]
# name = "python"
# language-servers = ["ruff"]

#========= pyright (pretty nice but no inlay hints)
# [language-server.pyright]
# command = "pyright-langserver"
# args = ["--stdio"]
# config = {} # buggy behaviour, you need a pyproject.toml and pyrightconfig.json

# [[language]]
# name = "python"
# formatter = { command = "black", args = ["--quiet", "-"] }
# auto-format = true
# roots = ["pyproject.toml"]
# language-servers = [ "pyright" ]

#================
[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
except-features = ["format", "code-action"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
typeCheckingMode = "basic" # this makes it quick!
diagnosticMode = "openFilesOnly"

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]
