# ========================= PYLSP===========
# [[language]]
# name = "python"
# language-servers = [ { name = "pylsp", except-features = [ "format" ] }, "ruff"]
# auto-format = true

# [language-server.pylsp.config.pylsp.plugins]
# ruff.enabled = false
# autopep8.enabled = false
# flake8.enabled = false
# mccabe.enabled = false
# pycodestyle.enabled = false
# pyflakes.enabled = false
# pylint.enabled = false
# yapf.enabled = false

#=================== Pyrefly============
# [language-server.pyrefly]
# command = "pyrefly"
# args = ["lsp"]

# [[language]]
# name = "python"
# language-servers = ["pyrefly"]
# 
# ========================= Based Pyright===========

# [language-server.basedpyright]
# command = "basedpyright-langserver"
# args = ["--stdio"]

# [language-server.basedpyright.config]
# basedpyright.analysis.diagnosticMode = "openFilesOnly"
# basedpyright.diagnostic.reportUnknownParameterType = "False"
# basedpyright.diagnostic.reportUnknownArgumentType = "False"
# basedpyright.diagnostic.reportUnknownVariableType = "False"
# basedpyright.diagnostic.reportUnknownLambdaType = "False"

# reportMissingParameterType = "False"

# [[language]]
# name = "python"
# language-servers = ["basedpyright"]


[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.basedpyright]
analysis.diagnosticMode = "openFilesOnly"
diagnostics.reportUnknownParameterType = "none"
diagnostics.reportUnknownArgumentType = "none"
diagnostics.reportUnknownLambdaType = "none"
diagnostics.reportUnknownVariableType = "none"
diagnostics.reportUnknownMemberType = "none"

[[language]]
name = "python"
language-servers = ["basedpyright"]
