
"ui.background" = { bg = "background" }
"ui.background.separator" = { bg = "background-1" }
"ui.cursor" = { fg = "foreground-3", bg = "orange" }
"ui.cursor.match" = { fg = "foreground-2", bg = "background-3" }
"ui.cursor.primary" = { fg = "foreground", bg = "background-3" }

"ui.linenr" = { fg = "foreground-3" }
"ui.linenr.selected" = { fg = "foreground" }

"ui.bufferline" = { fg = "foreground-2", bg = "background-2" }
"ui.bufferline.active" = { fg = "orange", bg = "background-2" }

"ui.statusline" = { fg = "foreground-2", bg = "background-3" }
"ui.statusline.inactive" = { fg = "foreground-3", bg = "background-1" }
"ui.statusline.normal" = { fg = "background", bg = "yellow" }
"ui.statusline.insert" = { fg = "background", bg = "green" }
"ui.statusline.select" = { fg = "background", bg = "blue" }

"ui.popup" = { bg = "background-2" }
"ui.popup.info" = { bg = "background-2" }

"ui.window" = { fg = "background-4", bg = "background" }
"ui.help" = { fg = "foreground-2", bg = "background-1" }

"ui.text" = { fg = "foreground" }
"ui.text.focus" = { bg = "background-3" }
"ui.text.info" = { fg = "foreground-2" }
"ui.text.directory" = { fg = "aqua" }

"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "background-3" }
"ui.virtual.whitespace" = { fg = "background-4" }
"ui.virtual.indent-guide" = { fg = "background-4" }
"ui.virtual.inlay-hint" = { fg = "foreground-3" }

"ui.menu" = { fg = "foreground-2", bg = "background-2" }
"ui.menu.selected" = { fg = "foreground" }
"ui.menu.scroll" = { fg = "foreground-3", bg = "background-3" }

"ui.selection" = { bg = "background-3" }
"ui.selection.primary" = { bg = "background-4" }

"ui.cursorline.primary" = { bg = "background-2" }
"ui.cursorline.secondary" = { bg = "background-1" }

"warning" = "yellow"
"error" = "red"
"info" = "blue"
"hint" = "aqua"
"debug" = "orange"

"diagnostic" = { underline = { color = "foreground-2", style = "curl" } }
"diagnostic.hint" = { underline = { color = "aqua", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"special" = "orange"

"attribute" = "purple"
"type" = "green"
"constructor" = "green"
"constant" = "green"
"constant.builtin" = "red"
"constant.builtin.boolean" = "yellow"
"constant.character" = "orange"
"constant.character.escape" = "aqua"
"constant.numeric" = "yellow"
"string" = "green"

"comment" = { fg = "gray", modifiers = ["italic"] }
"variable" = "foreground"
"variable.builtin" = "red"
"variable.parameter" = "purple"
"variable.other.member" = "aqua"
"label" = "green"
"punctuation" = "foreground-3"
"keyword" = "orange"
"keyword.operator" = "foreground-2"
"operator" = "foreground-2"

"function" = "blue"
"function.builtin" = "red"
"tag" = "yellow"
"namespace" = "foreground"

"markup.heading.marker" = "gray"
"markup.heading" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.1" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.2" = { fg = "green", modifiers = ["bold"] }
"markup.heading.3" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.4" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.5" = { fg = "purple", modifiers = ["bold"] }
"markup.heading.6" = { fg = "green", modifiers = ["bold"] }
"markup.list" = "gray"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = "aqua"
"markup.link.url" = { fg = "aqua", underline = { color = "aqua", style = "line" } }
"markup.link.label" = "foreground-2"
"markup.link.text" = "foreground"
"markup.quote" = "foreground-3"
"markup.raw" = "foreground-3"

"diff" = "background-4"
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

[palette]
red     = "#c65f5f"
green   = "#859e82"
yellow  = "#d9b27c"
blue    = "#728797"
purple  = "#998396"
aqua    = "#829e9b"
beige   = "#ab9382"
orange  = "#d08b65"
orange2 = "#241f1a"

gray          = "#3d3837"
background    = "#252221"
background-1  = "#262322"
background-2  = "#302c2b"
background-3  = "#3d3837"
background-4  = "#413c3a"

foreground    = "#c8baa4"
foreground-1  = "#cdc0ad"
foreground-2  = "#beae94"
foreground-3  = "#d1c6b4"
