"attribute" = "Green"

"type" = "Yellow"
"type.return" = "Green"
"type.parameter" = "Green"
"constructor" = "Orange"

"constant" = "Beige"
"constant.builtin.boolean" = "Aqua"
"constant.character" = "Yellow"
"constant.character.escape" = "Aqua"
"constant.numeric" = "Beige"
"string" = "Green"
"string.regexp" = "Aqua"
"string.special" = { fg = "Yellow", modifiers = ["underlined"] }


"ui.bufferline" = { fg = "Foreground2", bg = "Background1" }
"ui.bufferline.active" = { fg = "Orange", bg = "Background1" }

# "ui.gutter" = {bg= "Background2"}
# "ui.gutter.selected" = {bg = "Background2"}
"ui.virtual.jump-label" = {fg = "Orange", bg = "Background2"}

"comment" = {fg = "Background3", modifiers = ["italic"]} # .line
"variable" = "Foreground2"
"variable.builtin" = { fg = "Beige" }
"variable.other.member" = "Aqua"
"label" = "Yellow"
"keyword" = "Red2"
"function" = "Yellow"
"function.declaration" = "Foreground"
"function.macro" = "Red"
"function.builtin" = "Beige"
"function.special" = "Orange"

"tag" = "Green"
# "tag" = "Grey2"
"special" = "Red"
"namespace" = "Orange"

"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.heading" = { fg = "Yellow", modifiers = ["bold"] }
"markup.list" = "Green"
"markup.list.numbered" = "Aqua"
"markup.list.unnumbered" = "Aqua"
"markup.link.url" = { fg = "Aqua", modifiers = ['italic', 'underlined'] }
"markup.link.text" = "Blue"
"markup.link.label" = "Red2"
"markup.quote" = "Beige"
"markup.raw" = "Beige"
"markup.raw.inline" = "Aqua"
"markup.raw.block" = "Red2"

"diff.plus" = "Green"
"diff.minus" = "Red"
"diff.delta" = "Blue"

"ui.background" = { bg = "Background" }
"ui.statusline" = { fg = "Foreground1", bg = "Background1" }
"ui.statusline.inactive" = { fg = "Foreground2" }
"ui.statusline.normal" = { fg = "Background", bg = "Yellow" }
"ui.statusline.insert" = { fg = "Background", bg = "Red" }
"ui.statusline.select" = { fg = "Background", bg = "Orange" }

"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "Orange", bg = "Background3" }
"ui.selection" = { fg = "Foreground", bg = "Background2" }
"ui.selection.primary" = { fg = "Foreground", bg = "Background4" }

"ui.cursorline" = { bg = "Background1" }
"ui.linenr" = "Background2"
"ui.linenr.selected" = "Yellow"

"ui.picker.header.column" = "Red2"
"ui.picker.header.column.active" = "Green"

"ui.popup" = { fg = "Foreground", bg = "Background2" }
"ui.window" = { fg = "Gray" }
"ui.help" = { fg = "Foreground", bg = "Background2" }
"ui.menu" = { fg = "Foreground", bg = "Background2" }
"ui.menu.selected" = { fg = "Background", bg = "Blue" }
"ui.menu.scroll" = { fg = "Foreground2" }

"ui.text" = "Foreground"
"ui.text.focus" = { fg = "Yellow", bg = "Background3" }
"ui.text.directory" = { fg = "Orange"}

"ui.virtual" = "Foreground2"
"ui.virtual.indent-guide" = { fg = "Background4",modifiers=["dim"] }
"ui.virtual.inlay-hint" = { fg = "Brown", modifiers=["bold"]}
"ui.virtual.ruler" = { bg = "Background2" }

"hint" = "Foreground2"
"info" = "Red2"
"warning" = "Orange"
"error" = "Red"

"diagnostic.hint" = { underline = { color = "Foreground2", style = "line" } }
"diagnostic.info" = { underline = { color = "Red2", style = "line" } }
"diagnostic.warning" = { underline = { color = "Yellow", style = "line" } }
"diagnostic.error" = { underline = { color = "Red", style = "line" }}
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
Red          =  "#cf6363"  #hsl  0,   53,  60
Red2         =  "#bf616a"
Green        =  "#90be6d"
Yellow       =  "#cfa663"
Blue2        =  "#5e81ac"
Aqua         =  "#ffe0af"
Beige        =  "#858585"
Orange       =  "#d08b65"  #hsl  21,  53,  60
Gray         =  "#3d3837"
Gray2        =  "#827272"
Gray3        =  "#655555"
Brown        =  "#6a4f3b"

Background   =  "#2d2429"
Background1  =  "#322220"
Background2  =  "#4b3330"
Background3  =  "#704c48"
Background4  =  "#895d58"
Background5  =  "#563939"

Foreground   =  "#c8baa4"
Foreground1  =  "#cdc0ad"
Foreground2  =  "#beae94"
Foreground3  =  "#d1c6b4"
